
package au.com.optus.mcas.sdp.nbnenabler.model;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "NbnEnablerServiceEndpointService", targetNamespace = "http://www.group.singtel.com.au/optus/oss/enabler/NbnEnablerService/v4_0_0/NbnEnablerService", wsdlLocation = "file:/home/optus/git/nbn/nbn_enabler/nbn_enabler_service/src/main/resources/wsdl/NbnEnablerService.wsdl")
public class NbnEnablerServiceEndpointService
    extends Service
{

    private final static URL NBNENABLERSERVICEENDPOINTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(au.com.singtel.group.optus.oss.enabler.nbnenablerservice.v4_0_0.nbnenablerservice.NbnEnablerServiceEndpointService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = au.com.singtel.group.optus.oss.enabler.nbnenablerservice.v4_0_0.nbnenablerservice.NbnEnablerServiceEndpointService.class.getResource(".");
            url = new URL(baseUrl, "file:/home/optus/git/nbn/nbn_enabler/nbn_enabler_service/src/main/resources/wsdl/NbnEnablerService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/optus/git/nbn/nbn_enabler/nbn_enabler_service/src/main/resources/wsdl/NbnEnablerService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        NBNENABLERSERVICEENDPOINTSERVICE_WSDL_LOCATION = url;
    }

    public NbnEnablerServiceEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NbnEnablerServiceEndpointService() {
        super(NBNENABLERSERVICEENDPOINTSERVICE_WSDL_LOCATION, new QName("http://www.group.singtel.com.au/optus/oss/enabler/NbnEnablerService/v4_0_0/NbnEnablerService", "NbnEnablerServiceEndpointService"));
    }

    /**
     * 
     * @return
     *     returns NbnEnablerServiceEndpoint
     */
    @WebEndpoint(name = "NbnEnablerServiceEndpointPort")
    public NbnEnablerServiceEndpoint getNbnEnablerServiceEndpointPort() {
        return super.getPort(new QName("http://www.group.singtel.com.au/optus/oss/enabler/NbnEnablerService/v4_0_0/NbnEnablerService", "NbnEnablerServiceEndpointPort"), NbnEnablerServiceEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NbnEnablerServiceEndpoint
     */
    @WebEndpoint(name = "NbnEnablerServiceEndpointPort")
    public NbnEnablerServiceEndpoint getNbnEnablerServiceEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.group.singtel.com.au/optus/oss/enabler/NbnEnablerService/v4_0_0/NbnEnablerService", "NbnEnablerServiceEndpointPort"), NbnEnablerServiceEndpoint.class, features);
    }

}
