
package au.com.optus.mcas.sdp.nbnapp.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "BusinessException", targetNamespace = "http://www.group.singtel.com.au/cdm/v2_0_0/exception")
public class BusinessException
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BusinessException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public BusinessException(String message, BusinessException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public BusinessException(String message, BusinessException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: au.com.singtel.group.cdm.v2_0_0.exception.BusinessException
     */
    public BusinessException getFaultInfo() {
        return faultInfo;
    }

}
